import dynamic from "next/dynamic";
import { Inter } from "next/font/google";
import "./globals.css";

const Navbar = dynamic(() => import("./(components)/Navbar"), { ssr: false });

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <Navbar />
        <div className="max-w-[1060px] mx-auto">{children}</div>
        <div className="h-[200px]"></div>
      </body>
    </html>
  );
}
